CREATE TABLE OAUTH_CLIENT_DETAILS
(
    CLIENT_ID               VARCHAR(255) PRIMARY KEY,
    RESOURCE_IDS            VARCHAR(255),
    CLIENT_SECRET           VARCHAR(255),
    SCOPE                   VARCHAR(255),
    AUTHORIZED_GRANT_TYPES  VARCHAR(255),
    WEB_SERVER_REDIRECT_URI VARCHAR(255),
    AUTHORITIES             VARCHAR(255),
    ACCESS_TOKEN_VALIDITY   INT,
    REFRESH_TOKEN_VALIDITY  INT,
    ADDITIONAL_INFORMATION  TEXT,
    AUTOAPPROVE             VARCHAR(255)         DEFAULT 'true',
    CREATE_TIME             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATE_TIME             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);